name: Build Windows x86 with Conveyor

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Linux runner is sufficient and cost-effective for Windows builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17  # Adjust version if your project uses a different JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # Or 'zulu', etc., based on your needs
          java-version: '17'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew :desktop:build

      - name: Package with Conveyor
        uses: hydraulic-software/conveyor/actions/build@v19.0  # Use the latest version; confirm on https://github.com/hydraulic-software/conveyor
        with:
          command: -Kapp.machines=windows.amd64 make windows-zip
          agree_to_license: 1  # Required to accept the Conveyor EULA

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x86-binary
          path: output/  # Adjust if your output folder is different; the build instructions say it's in the project root
