name: Desktop Build

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Latest Release
        id: release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          view_top: 1

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v1
        with:
          command: make site
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          conveyor_version: '9.1'

      - name: Upload Release Files
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'output/*'
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: false
          omitBodyDuringUpdate: true
          tag: ${{ steps.release.outputs.tag_name }}